### PR TITLE
Mem/disk mib fix and unit test

### PR DESCRIPTION
**Pull request by hermidalc**
### QC

* [x] The PR contains a test case for the changes or the changes are already covered by an existing test case.
* [x] The documentation (`docs/`) is updated to reflect the changes or this is not necessary (e.g. if the change does neither modify the language nor the behavior or functionalities of Snakemake).

### CODE REVIEW

**Comment by BEFH** [comment]
maybe we should also test the calculation of `mem_mb` from `mem` when `mem` is in `GB/TB`? I changed that code as well. Also, is there any way you can do the PR to the [mem_disk_fix](https://github.com/BEFH/snakemake/tree/mem_disk_fix) branch instead of the main branch? Otherwise, I do not think anything else is required.

For `mem="1 GB"`, `mem_mb` should be 1000 now and `mem_mib` should  be 954. This might work to test everything but I don't know if it makes sense to have separate tests for each thing.

**Comment by hermidalc** [comment]
> maybe we should also test the calculation of `mem_mb` from `mem` when `mem` is in `GB/TB`? I changed that code as well. Also, is there any way you can do the PR to the [mem_disk_fix](https://github.com/BEFH/snakemake/tree/mem_disk_fix) branch instead of the main branch? Otherwise, I do not think anything else is required.
> 
> For `mem="1 GB"`, `mem_mb` should be 1000 now and `mem_mib` should be 954. This might work to test everything but I don't know if it makes sense to have separate tests for each thing.

Sorry if I'm not up-to-date on standards, but for `disk` I would expect I think 1 GB == 1000 but not for `mem`? I think that should be 1024 still?

**Comment by BEFH** [comment]
The issue is that the code is currently fixed but extremely literal. If you specify G or GB (technically an SI unit), it's GB. If you specify GiB, it's the binary unit. I don't know why you would ever would want to use SI units for memory, so what you're saying is potentially a good idea, but it also potentially breaks the distinction between `mem_mb` and `mem_mib`. A happy medium would be to assume binary in `mem` but not in `disk` when using `humanfriendly.parse_size()`

**Comment by hermidalc** [comment]
> The issue is that the code is currently fixed but extremely literal. If you specify G or GB (technically an SI unit), it's GB. If you specify GiB, it's the binary unit. I don't know why you would ever would want to use SI units for memory, so what you're saying is potentially a good idea, but it also potentially breaks the distinction between `mem_mb` and `mem_mib`. A happy medium would be to assume binary in `mem` but not in `disk` when using `humanfriendly.parse_size()`

Definitely should keep with the existing impl to not break people's code. I just tested it on 8.16 and `4 GB` yields `mem_mb=3815`

**Comment by BEFH** [comment]
4 GB yielding `mem_mb=3815` is incorrect behavior. It should be either 4000 or 4295 depending on implementation. The current value is a huge bug.

**Comment by hermidalc** [comment]
> 4 GB yielding `mem_mb=3815` is incorrect behavior. It should be either 4000 or 4295 depending on implementation. The current value is a huge bug.

Yep I tested it with local and on the slurm cluster and 4G is 3815 MB in Snakemake 8.16, odd. I guess your fix will correct that too?

**Comment by BEFH** [comment]
I fixed that in my first commit, or at least should have. They were doing
the mib calculation for mb.

**Comment by hermidalc** [comment]
I added gb and tb to mib tests

**Comment by BEFH** [comment]
Thanks! is there any way you could change the base branch for the pull request from main to [mem_disk_fix](https://github.com/hermidalc/snakemake/tree/mem_disk_fix)?

**Comment by hermidalc** [comment]
> Thanks! is there any way you could change the base branch for the pull request from main to [mem_disk_fix](https://github.com/hermidalc/snakemake/tree/mem_disk_fix)?

Damn I don't know why it did that I was working locally on the mem_disk_fix branch I just double checked it. Have to figure out how to change it

**Comment by hermidalc** [comment]
Thank you @BEFH it didn't look like I had the permissions to do it because I didn't get a dropdown menu to change the base branch I can only see a link there

**Comment by BEFH** [comment]
I figured out how to change it myself. I will be adding the MB to the outputs as well.

**Pull request merged**
